server:
  port: 8080

spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

#Swagger lock
swagger:
  enable: true







