spring:
  profiles:
    active: dev

  # mysql 配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    schema:
      - classpath:oauth2.sql


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mappers/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

http-client:
  #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
  maxTotalConnect: 1000
  #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
  maxConnectPerRoute: 200
  # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
  connectTimeout: 3000
  # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
  readTimeout: 5000
  # 从连接池获取连接的timeout,不宜过大,ms
  connectionRequestTimout: 200
  # 重试次数
  retryTimes: 3
  charset: UTF-8
  # 长连接保持时间 单位s,不宜过长
  keepAliveTime: 10

# 权限
auth:
  # AES密码加密私钥(Base64加密)
  encryptAESKey: a7SDfrdDKRBe5FaN2n3Gfg==














